# ******************************************************** #
#           AUTO-GENERATED. DO NOT EDIT THIS FILE.         #
# ******************************************************** #
#    Create your files in `resources/docs/apidoc/manual`   #
# ******************************************************** #
###
@apiVersion 1.0.0
@api {POST} api/v1/register Register
@apiGroup Auth
@apiParam {String} device_id Unique ID of the device
@apiParam {String} device_type Type of the device `APPLE` or `ANDROID`
@apiParam {String} [device_push_token] Unique push token for the device
@apiParam {String} email Email address of user
@apiParam {String} password Password. Must be at least 8 characters.
@apiUse default_headers
###
# ******************************************************** #
#           AUTO-GENERATED. DO NOT EDIT THIS FILE.         #
# ******************************************************** #
#    Create your files in `resources/docs/apidoc/manual`   #
# ******************************************************** #
###
@apiVersion 1.0.0
@api {POST} api/v1/login Login
@apiGroup Auth
@apiParam {String} device_id Unique ID of the device
@apiParam {String} device_type Type of the device `APPLE` or `ANDROID`
@apiParam {String} [device_push_token] Unique push token for the device
@apiParam {String} email Email
@apiParam {String} password Password
@apiHeader {String} Accept `application/json`
@apiHeader {String} x-api-key API Key
###
# ******************************************************** #
#           AUTO-GENERATED. DO NOT EDIT THIS FILE.         #
# ******************************************************** #
#    Create your files in `resources/docs/apidoc/manual`   #
# ******************************************************** #
###
@apiVersion 1.0.0
@api {POST} api/v1/verify-email/verify Email Verification
@apiGroup Auth
@apiParam {String} code Verification Code
@apiUse default_headers
@apiSuccessExample {json} Success-Response / HTTP 200 OK
{
					"payload": {
						"uuid": "a3bcf5f0-3b7c-4a0d-8c63-1ba604a76f8f",
						"last_name": null,
						"email": "alokadevapriya@gmail.com",
						"dob": null,
						"address": null,
						"avatar_url": null,
						"first_name": null,
						"full_name": "",
						"is_verified": true,
						"role": "buyers"
					},
					"message": "",
					"result": true
				}
###
# ******************************************************** #
#           AUTO-GENERATED. DO NOT EDIT THIS FILE.         #
# ******************************************************** #
#    Create your files in `resources/docs/apidoc/manual`   #
# ******************************************************** #
###
@apiVersion 1.0.0
@api {GET} api/v1/resend-code Resend Verification Code
@apiGroup Auth
@apiUse default_headers
###
# ******************************************************** #
#           AUTO-GENERATED. DO NOT EDIT THIS FILE.         #
# ******************************************************** #
#    Create your files in `resources/docs/apidoc/manual`   #
# ******************************************************** #
###
@apiDescription Logout the user from current device
@apiVersion 1.0.0
@api {GET} api/v1/logout Logout
@apiGroup Auth
@apiUse default_headers
###
# ******************************************************** #
#           AUTO-GENERATED. DO NOT EDIT THIS FILE.         #
# ******************************************************** #
#    Create your files in `resources/docs/apidoc/manual`   #
# ******************************************************** #
###
@apiVersion 1.0.0
@api {POST} api/v1/password/edit Update Password
@apiGroup Auth
@apiParam {String} password Password
@apiParam {String} current_password Current password
@apiParam {String} password_confirmation Password confirmation
@apiUse default_headers
###
