# ******************************************************** #
#           AUTO-GENERATED. DO NOT EDIT THIS FILE.         #
# ******************************************************** #
#    Create your files in `resources/docs/apidoc/manual`   #
# ******************************************************** #
###
@apiVersion 1.0.0
@api {POST} api/v1/password/email Reset Password
@apiGroup ForgotPassword
@apiParam {String} email Email
@apiHeader {String} Accept `application/json`
@apiHeader {String} x-api-key API Key
@apiErrorExample {json} Error-Response / HTTP 422 Unprocessable Content
{
					"message": "Failed to send password reset email. Ensure your email is correct and try again.",
					"payload": null,
					"result": false
				}
###
