# ******************************************************** #
#           AUTO-GENERATED. DO NOT EDIT THIS FILE.         #
# ******************************************************** #
#    Create your files in `resources/docs/apidoc/manual`   #
# ******************************************************** #
###
@apiDescription Guest settings and parameters
@apiVersion 1.0.0
@api {GET} api/v1/guests Guest Settings
@apiGroup Guest
@apiHeader {String} Accept `application/json`
@apiHeader {String} x-api-key API Key
###
