# ******************************************************** #
#           AUTO-GENERATED. DO NOT EDIT THIS FILE.         #
# ******************************************************** #
#    Create your files in `resources/docs/apidoc/manual`   #
# ******************************************************** #
###
@apiDescription Get currently logged in user's profile
@apiVersion 1.0.0
@api {GET} api/v1/profile My Profile
@apiGroup Profile
@apiUse default_headers
###
# ******************************************************** #
#           AUTO-GENERATED. DO NOT EDIT THIS FILE.         #
# ******************************************************** #
#    Create your files in `resources/docs/apidoc/manual`   #
# ******************************************************** #
###
@apiVersion 1.0.0
@api {PUT} api/v1/profile Update My Profile
@apiGroup Profile
@apiParam {String} first_name First name
@apiParam {String} [last_name] Last name
@apiParam {String} email Email
@apiParam {String} [phone] Phone
@apiUse default_headers
###
# ******************************************************** #
#           AUTO-GENERATED. DO NOT EDIT THIS FILE.         #
# ******************************************************** #
#    Create your files in `resources/docs/apidoc/manual`   #
# ******************************************************** #
###
@apiVersion 1.0.0
@api {POST} api/v1/avatar Update My Avatar
@apiGroup Profile
@apiParam {File} image Image
@apiUse default_headers
###
