# ******************************************************** #
#           AUTO-GENERATED. DO NOT EDIT THIS FILE.         #
# ******************************************************** #
#    Create your files in `resources/docs/apidoc/manual`   #
# ******************************************************** #
###
@apiDescription Returns all app settings. Each setting value is identified by the respective key.
@apiVersion 1.0.0
@api {GET} api/v1/settings Get Settings
@apiGroup Settings
@apiHeader {String} Accept `application/json`
@apiHeader {String} x-api-key API Key
@apiSuccessExample {json} Success-Response / HTTP 200 OK
{
    "payload": {
        "settings": [
            {
                "id": 1,
                "created_at": "2020-06-17T11:05:27.000000Z",
                "updated_at": "2020-06-17T11:05:27.000000Z",
                "key": "ABOUT_US",
                "value": null
            },
            {
                "id": 2,
                "created_at": "2020-06-17T11:05:27.000000Z",
                "updated_at": "2020-06-17T11:05:27.000000Z",
                "key": "PRIVACY_POLICY",
                "value": null
            },
            {
                "id": 3,
                "created_at": "2020-06-17T11:05:27.000000Z",
                "updated_at": "2020-06-17T11:05:27.000000Z",
                "key": "TERMS_AND_CONDITIONS",
                "value": null
            }
        ]
    },
    "message": "",
    "result": true
}
###
# ******************************************************** #
#           AUTO-GENERATED. DO NOT EDIT THIS FILE.         #
# ******************************************************** #
#    Create your files in `resources/docs/apidoc/manual`   #
# ******************************************************** #
###
@apiDescription Returns the value of a single app setting requested by key.
@apiVersion 1.0.0
@api {GET} api/v1/settings/{key} Get Setting
@apiGroup Settings
@apiParam {String} key Key of the setting
@apiUse default_headers
@apiSuccessExample {json} Success-Response / HTTP 200 OK
{
    "payload": {
        "id": 1,
        "created_at": "2020-06-17T11:05:27.000000Z",
        "updated_at": "2020-06-17T11:05:27.000000Z",
        "key": "ABOUT_US",
        "value": null
    },
    "message": "",
    "result": true
}
###
